spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: Jusda#123
    driver-class-name: com.mysql.cj.jdbc.Driver
